add PerfCCT frame, record inst lifetime
OpenXiangShan/Utility pull request #88
Opened 2024-11-28 10:39 UTC by tastynoob

[WIP]
One general performance framework
Record large structure by c++ layer
And easy to expand and maintain

2024-11-28 10:50 UTC, tastynoob commented
Use this framework need to implement "global simulation tick" and "riscv disasm" two function in verilator c++ layer,
I learned that there is a function called GTimer, but it looks cumbersome
I have one ideal like this
![image](https://github.com/user-attachments/assets/53c2ba9b-0762-4c33-b086-cae3bdfa0976)
(difftest/src/test/csrc/common/main.cpp)
Increment when call emu->tick()

2025-02-10 10:54 UTC, tastynoob commented on src/main/scala/utility/ChiselPerfCCT.scala
> +trait HasDPICAssign extends BlackBox with HasBlackBoxInline {
Why here need one new trait

2025-02-10 10:54 UTC, tastynoob commented on src/main/scala/utility/ChiselPerfCCT.scala
> +trait HasDPICAssign extends BlackBox with HasBlackBoxInline {
Can we reuse trait HasDPIC?

2025-02-11 01:44 UTC, sinceforYy commented on src/main/scala/utility/ChiselPerfCCT.scala
> +trait HasDPICAssign extends BlackBox with HasBlackBoxInline {
For createInstMeta, we need to get sn in the current clock, not on the next clock posedge. We should use combinational logic to implement it.

2025-02-11 01:48 UTC, sinceforYy commented on src/main/scala/utility/ChiselPerfCCT.scala
> +trait HasDPICAssign extends BlackBox with HasBlackBoxInline {
Since the formats are different, they should not be reused.

2025-02-11 02:11 UTC, tastynoob commented on src/main/scala/utility/ChiselPerfCCT.scala
> +trait HasDPICAssign extends BlackBox with HasBlackBoxInline {
I mean use parameterization, make HasDPICAssign merge to HasDPICUnit

2025-03-19 03:46 UTC, Lemover reviewed
Great Jobs. This work will help a lot.

I have several questions:
1. whereis the defination and usage of riscv-disasm. (According to the "mush define here").
Module "difftest" has a method "spikedasm", is it?
2. Does the global_tick_acc kepp consistent with dut's tick? Have you ever check it?
3. The pr message should be written and ready before ready for code-review. The pr changes a lot, involving many repos. Is there any XiangShan's pr?
4. Is the any usage examples to show (workable, effectiveness, etc)
5. Is the corespoding documents about how to use it and upgrade it?

2025-03-19 03:59 UTC, Lemover approved these changes

2025-03-19 04:01 UTC, tastynoob commented
question 1: Since the riscv-disasm of difftest is implemented by calling spike, I think the efficiency of disassembly at runtime will be very poor, now we disasm only when analyzing
question 2: Yes
question 4-5: Not yet documented
question 6: About 2~4 GB
question 7: Yes

2025-03-19 04:21 UTC, poemonsense requested changes
You first need to address the comments from @Lemover, including the definition and source of `riscv_disasm`.  If you think spikedasm can be improved, do it first and separately, instead of leaving it nowhere. You also need to format the commit messages as stated in question 3.

Beside, this looks too much from my side. I will not accept such changes based on its current code quality.

Why does a ChiselDB object create a PerfCCT? What's their relationship? What if the user does not want PerfCCT but only ChiselDB?

There are even TODOs in the C++ code.

Have you tried build the source with XiangShan and difftest? You have to clearly documented or at least said something in the PR, telling the others how they can use this tool and how this affects the RTL design. This is also what Lemover has said.

Getting an Approve does not mean that you can simply respond to it and does nothing to improve the code

2025-03-19 08:38 UTC, tastynoob commented
The Xiangshan's pr https://github.com/OpenXiangShan/XiangShan/pull/4007.
And the "TODO" is actually a "interface example", now modify the comments.
PerfCCT now reuse ChiselDB's logic and switch, PerfCCT also be compiled if ChiselDB was compiled.
Use "--dump-select-db lifetime" to only dump the PerfCCT's trace

2025-03-20 07:10 UTC, poemonsense approved these changes
Other implementations need refactor in the future

2025-03-27 05:11 UTC, merged